issue/3163 Added _isItemScoring
adaptlearning/adapt-contrib-mcq pull request #161
Opened 2021-06-15 15:32 UTC by oliverfoster

part of https://github.com/adaptlearning/adapt_framework/pull/3172

### Added
* `_isItemScoring` support

2021-06-16 13:28 UTC, tomgreenfield requested changes

2021-06-16 13:28 UTC, tomgreenfield commented on properties.schema
> +            "title": "Attempts",
```suggestion
            "title": "Score",
```

2021-06-16 13:28 UTC, tomgreenfield commented on README.md
> +**\_questionWeight** (number): When '_hasItemScoring' is `false`, this is the question score for a correct response. This number is used in calculations of the final score reported to the LMS.
```suggestion
**\_questionWeight** (number): When `_hasItemScoring` is `false`, this is the question score for a correct response. This number is used in calculations of the final score reported to the LMS.  
```

2021-06-16 13:28 UTC, tomgreenfield commented on README.md
> +**\_hasItemScoring** (boolean): When `false`, this question scores 0 for incorrect and 'Question Weight' for correct. When `true`, this question scores by summing the `_score` of the selected items.
```suggestion
**\_hasItemScoring** (boolean): When `false`, this question scores 0 for incorrect and '`_questionWeight` for correct. When `true`, this question scores by summing the `_score` of the selected items.  
```

2021-06-16 13:28 UTC, tomgreenfield commented on README.md
> +>**\_score** (boolean): If 'Item Scoring' is `true`, when selected, item scores are summed to give the question score.
```suggestion
>**\_score** (number): If `_hasItemScoring` is `true`, when selected, item scores are summed to give the question score.  
```

2021-06-16 13:28 UTC, tomgreenfield commented on properties.schema
> +      "title": "Item Scoring",
```suggestion
      "title": "Enable item scoring",
```

2021-06-16 13:28 UTC, tomgreenfield commented on properties.schema
> +      "help": "When 'Item Scoring' is disabled, this is the question score for a correct response."
```suggestion
      "help": "When item scoring is disabled, this is the question score for a correct response."
```

2021-06-16 13:28 UTC, tomgreenfield commented on properties.schema
> +            "help": "If 'Item Scoring' is enabled, when selected, item scores are summed to give the question score."
```suggestion
            "help": "If item scoring is enabled, selected item scores are summed to give the question score."
```

2021-06-18 10:04 UTC, tomgreenfield approved these changes

2021-06-18 16:02 UTC, cahirodoherty-learningpool approved these changes
👀

2021-06-22 09:13 UTC, eleanor-heath approved these changes

2021-06-22 09:22 UTC, merged