Chore: e2e tests on mcq component (Issue/218)
adaptlearning/adapt-contrib-mcq pull request #219
Opened 2024-03-26 19:43 UTC by lemmyadams

Addresses #218

2024-03-27 09:27 UTC, cahirodoherty-learningpool approved these changes
👀

2024-03-27 11:01 UTC, lemmyadams commented
Relies on https://github.com/adaptlearning/adapt_framework/pull/3533

2024-03-28 12:22 UTC, ethan-lp approved these changes

2024-04-08 11:55 UTC, oliverfoster commented
Brackets, line endings and odd whitespace and compiled html properties.

2024-04-08 16:26 UTC, joe-allen-89 requested changes

2024-04-08 16:26 UTC, joe-allen-89 commented on test/e2e/mcq.cy.js
> +    mcqComponents.forEach((mcqComponent) => {
We can remove the additional brackets from the arrow functions. 

```suggestion
    const mcqComponents = this.data.components.filter(component => component._component === 'mcq')
    mcqComponents.forEach(mcqComponent => {
```

2024-04-08 16:26 UTC, joe-allen-89 commented on test/e2e/mcq.cy.js
> +      mcqComponent._items.forEach((item) => {
```suggestion
      mcqComponent._items.forEach(item => {
```

2024-04-11 13:35 UTC, oliverfoster commented on test/e2e/mcq.cy.js
> +        cy.testContainsOrNotExists('.mcq-item__text', item.text);
```suggestion
        cy.testContainsOrNotExists('.mcq-item__text', stripHtml(item.text));
```

Also compiled html 
https://github.com/adaptlearning/adapt-contrib-mcq/blob/f585154e6778e065855bea97365c1792f0b8af2e/templates/mcq.jsx#L109

2024-04-11 14:27 UTC, merged